{
 "title": "API Metrics",
 "tags": [
  "metrics",
  "prometheus",
  "spring",
  "api"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(process_uptime_seconds{application=\"otel-example-spring-java\"}, environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"otel-example-spring-java\",environment=~\"${environment}\",uri!=\"/actuator/prometheus\"}[$__range]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (uri) (increase(http_server_requests_seconds_count{application=\"otel-example-spring-java\",environment=~\"${environment}\",uri!=\"/actuator/prometheus\"}[$__range]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (uri) (increase(http_server_requests_seconds_sum{application=\"otel-example-spring-java\",environment=~\"${environment}\",uri!=\"/actuator/prometheus\"}[$__range])) / clamp_min(sum by (uri) (increase(http_server_requests_seconds_count{application=\"otel-example-spring-java\",environment=~\"${environment}\",uri!=\"/actuator/prometheus\"}[$__range])), 1)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"otel-example-spring-java\",environment=~\"${environment}\",uri!=\"/actuator/prometheus\",outcome=\"SERVER_ERROR\"}[$__range]))",
     "legendFormat": "exceptions"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (uri) (http_server_requests_seconds_count{application=\"otel-example-spring-java\",environment=~\"${environment}\",status=~\"2..\",uri!=\"/actuator/prometheus\"}) / clamp_min(sum by (uri) (http_server_requests_seconds_count{application=\"otel-example-spring-java\",environment=~\"${environment}\",uri!=\"/actuator/prometheus\"}), 1)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (uri) (http_server_requests_seconds_count{application=\"otel-example-spring-java\",environment=~\"${environment}\",status=~\"5..\",uri!=\"/actuator/prometheus\"}) / clamp_min(sum by (uri) (http_server_requests_seconds_count{application=\"otel-example-spring-java\",environment=~\"${environment}\",uri!=\"/actuator/prometheus\"}), 1)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "P99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (uri, le) (rate(http_server_requests_seconds_bucket{application=\"otel-example-spring-java\",environment=~\"${environment}\",uri!=\"/actuator/prometheus\"}[$__rate_interval])))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "P95 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (uri, le) (rate(http_server_requests_seconds_bucket{application=\"otel-example-spring-java\",environment=~\"${environment}\",uri!=\"/actuator/prometheus\"}[$__rate_interval])))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{application=\"otel-example-spring-java\",environment=~\"${environment}\"}[$__rate_interval]))",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}