spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      javax.persistence.query.timeout: 5000
      hibernate.connection.isolation: 4

    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;
    username: root
    password: toor
