[tool.ruff]
indent-width = 4  # 들여쓰기 공백 수
line-length = 100 # 한 줄 최대 길이
select = [# 활성화할 린트 규칙
    "E", # 에러
    "F", # 치명적 에러
    "W", # 경고
    "PIE", # 파이썬 아이디엄
    "C4", # 컴플렉스
    "ISC", # 임포트 스타일 체크
    "A", # 애너테이션
    "B", # 버그
    "NPY", # 넘파이
    "UP", # 업그레이드
    "TRY203", "TRY400", "TRY401", # try-except 관련 규칙
    "TID251", # 타입 체크
    "PLR1704", # 파이썬 린트 규칙
    "I", # 임포트 순서
    "E402"  # 모듈 수준 임포트
]

[tool.ruff.isort]  # 임포트 정렬 설정
combine-as-imports = true  # as 임포트 결합
force-single-line = false  # 강제 한 줄 임포트 비활성화
order-by-type = true  # 타입별 정렬
case-sensitive = true  # 대소문자 구분
force-wrap-aliases = true  # 별칭 강제 줄바꿈
split-on-trailing-comma = true  # 후행 쉼표에서 분할
lines-after-imports = 2  # 임포트 후 빈 줄 수
no-lines-before = ["LOCALFOLDER"]  # 특정 섹션 전 빈 줄 제거
section-order = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]  # 섹션 순서

[tool.ruff.lint]
ignore = [# 무시할 린트 규칙
    "E741", # 모호한 변수명
    "C408", # 불필요한 dict 호출
    "ISC003", # 임포트 스타일
    "B027", # 빈 메서드
    "B024", # 추상 메서드 구현
    "NPY002", # 넘파이 관련
    "UP038", # 업그레이드 관련
    "W293", # 빈 줄에 공백
    "UP015", # 라이브러리 함수에서 불필요한 기본 인자 제거 (open의 'r' 모드 등)
    "RUF003", # 백슬래시 이스케이프 문자 관련
    "RUF100", # 불필요한 이스케이프 시퀀스 제거
    "RUF008", # 불필요한 이스케이프 시퀀스 제거
    "W605", # 불필요한 문자열 리터럴
]
