spring:
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/bank?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
      read-only: false
      username: root
      password: 12345678
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3307/bank?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
      read-only: true
      username: root
      password: 12345678
