services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: otel-example-spring-java-app
    ports:
      - "8080:8080"
    depends_on:
      otel-collector:
        condition: service_started

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.123.0
    container_name: otel-example-spring-java-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel/otel-collector.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"
    depends_on:
      tempo:
        condition: service_started
      loki:
        condition: service_started

  tempo:
    image: grafana/tempo:2.7.2
    container_name: otel-example-spring-java-tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./otel/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"

  loki:
    image: grafana/loki:3.4.2
    container_name: otel-example-spring-java-loki
    command: ["-config.file=/etc/loki/local-config.yaml"]
    volumes:
      - ./otel/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: otel-example-spring-java-prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.6.0
    container_name: otel-example-spring-java-grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_started
      tempo:
        condition: service_started
      loki:
        condition: service_started

volumes:
  grafana-data:
  loki-data:
