services:
  mysql-primary:
    image: mysql:latest
    container_name: mysql-primary
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: bank
    volumes:
      - ./infra/db/primary/conf/my.cnf:/etc/mysql/my.cnf
      - ./infra/db/certs:/etc/mysql/ssl
    ports:
      - "3306:3306"
    networks:
      - mysql-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1GB

  primary-exporter:
    image: prom/mysqld-exporter:latest
    container_name: primary-exporter
    restart: always
    environment:
      - DATA_SOURCE_NAME="root:12345678@(mysql-primary:3306)/"
    command:
      - "--mysqld.username=root:12345678"
      - "--mysqld.address=mysql-primary:3306"
      - "--collect.perf_schema.eventsstatements"
    ports:
      - "9104:9104"
    networks:
      - mysql-network
    depends_on:
      - mysql-primary

  mysql-secondary:
    image: mysql:latest
    container_name: mysql-secondary
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: bank
    volumes:
      - ./infra/db/secondary/conf/my.cnf:/etc/mysql/my.cnf
      - ./infra/db/certs:/etc/mysql/ssl
    ports:
      - "3307:3306"
    networks:
      - mysql-network
    depends_on:
      - mysql-primary
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1GB

  secondary-exporter:
    image: prom/mysqld-exporter:latest
    container_name: secondary-exporter
    restart: always
    environment:
      - DATA_SOURCE_NAME="root:12345678@(mysql-secondary:3306)/"
    command:
      - "--mysqld.username=root:12345678"
      - "--mysqld.address=mysql-secondary:3306"
      - "--collect.perf_schema.eventsstatements"
    ports:
      - "9105:9104"
    networks:
      - mysql-network
    depends_on:
      - mysql-secondary

  grafana:
    image: bitnami/grafana:latest
    container_name: grafana
    ports:
      - "4885:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=df159357
    networks:
      - mysql-network

  prometheus:
    ports:
      - "9090:9090"
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./infra/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - mysql-network
    depends_on:
      - primary-exporter
      - secondary-exporter

networks:
  mysql-network:
    driver: bridge
