services:
  mysql-primary:
    image: mysql:latest
    container_name: mysql-primary
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: bank
    volumes:
      - ./infra/db/primary/conf/my.cnf:/etc/mysql/my.cnf
      - ./infra/db/certs:/etc/mysql/ssl
    ports:
      - "3306:3306"
    networks:
      - mysql-network

  mysql-secondary:
    image: mysql:latest
    container_name: mysql-secondary
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: bank
    volumes:
      - ./infra/db/secondary/conf/my.cnf:/etc/mysql/my.cnf
      - ./infra/db/certs:/etc/mysql/ssl
    ports:
      - "3307:3306"
    networks:
      - mysql-network
    depends_on:
      - mysql-primary

  grafana:
    image: bitnami/grafana:latest
    container_name: grafana
    ports:
      - "4885:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=df159357
    networks:
      - mysql-network

  prometheus:
    ports:
      - "9090:9090"
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./infra/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - mysql-network
networks:
  mysql-network:
    driver: bridge
