spring:
  application:
    name: kafka-az
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/kafka_az
    username: kafka_az
    password: kafka_az
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kafka-az
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  docker:
    compose:
      file: compose.yaml
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

outbox:
  relay:
    enabled: true
    delay-ms: 1000
