spring:
  datasource:
    url: jdbc:mysql://localhost:6603/mybatis?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: df159357

