global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 4s  # evaluation interval보다 크면 안됨

scrape_configs:
  - job_name: 'primary-exporter'
    static_configs:
      - targets: ['primary-exporter:9104']
  - job_name: 'secondary-exporter'
    static_configs:
      - targets: ['secondary-exporter:9104']
